services:
  backend:
    build: ./backend
    container_name: airline_backend
    ports:
      - "5000:5000"
    env_file:
      - ./backend/.env
    networks:
      - airline_network
    volumes:
      - ./backend:/app
      - /app/node_modules

  frontend:
    build: ./frontend
    container_name: airline_frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend
    networks:
      - airline_network
    volumes:
      - ./frontend:/app
      - /app/node_modules

networks:
  airline_network:
    driver: bridge
